### PR TITLE
Properly initialize SDKClient actions map

### LINKED ISSUE #519: [BUG] SDKClient execute() fails with NPE
### What is the bug?

SDKClient use of `execute()` implemented in #491 fails with NPE (`actions` is null) here:
```java
TransportAction<Request, Response> transportAction = actions.get(action);
```
The root cause is that we incorrectly attempt to access an injected `actions` map:
```java
// Used by client.execute
@SuppressWarnings("rawtypes")
@Inject
private Map<ActionType, TransportAction> actions;
```
However, the `SDKClient` was instantiated before injection so the map wasn't injected.

### How can one reproduce the bug?

1. Run an extension and use the `execute()` method from `SDKClient` or `SDKRestClient`.
2. Observe REST error response that "actions" is null.

### What is the expected behavior?
`actions.get(action)` returns an instance of a class implementing `TransportAction`.

### Do you have any additional context?

The implementation was ported from `NodeClient` with this field populated by the `initialize()` method (and not by injection):
```java
private Map<ActionType, TransportAction> actions;
```
This code from `Node.java` was not included in `ExtensionsRunner` shortly after injection completes, so porting it should fix this bug:
```java
client.initialize(injector.getInstance(new Key<Map<ActionType, TransportAction>>() {}));
```

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

Adds an `initialize()` method to the `SDKClient` to allow its `actions` map to be populated after Guice injection, even though the class was instantiated before.  This is the same pattern used with `NodeClient` that we are emulating.

In addition, maintains a field for the Guice `Injector` in the `ExtensionsRunner`.  It was getting garbage collected and losing its usefulness, particularly in Rest Handlers.

### Issues Resolved

Fixes #519

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by owaiskazi19 — DISMISSED** [review]

File: src/main/java/org/opensearch/sdk/SDKClient.java [hunk 1]
```diff
@@ -250,6 +253,9 @@ public final <Request extends ActionRequest, Response extends ActionResponse> vo
         Request request,
         ActionListener<Response> listener
     ) {
+        if (actions == null) {
```
Comment (owaiskazi19) [inline src/main/java/org/opensearch/sdk/SDKClient.java:256]: Do we need this check? Just for my understanding, what if there's an extension which doesn't have `getActions` extension point?

Comment (dbwiddis) [reply src/main/java/org/opensearch/sdk/SDKClient.java:256]: > Do we need this check? Just for my understanding, what if there's an extension which doesn't have `getActions` extension point?

Then they shouldn't call `client.execute()` and this gives them a more useful error message than the NPE.

Comment (dbwiddis) [reply src/main/java/org/opensearch/sdk/SDKClient.java:256]: Another possibility is just to initialize with an empty map so you don't get the NPE but you'd still get the "unregistered action" error.

Comment (owaiskazi19) [reply src/main/java/org/opensearch/sdk/SDKClient.java:256]: Makes sense!

**Review by owaiskazi19 — APPROVED** [review]

File: src/main/java/org/opensearch/sdk/SDKClient.java (hunk 1 above)
Comment (joshpalis) [reply src/main/java/org/opensearch/sdk/SDKClient.java:256]: +1, There are several use cases in which Plugins/Extensions need to trigger client.execute to invoke actions provided by OpenSearch, such as `UpdateByQueryAction`. We should still allow this without requiring an extension to provide its own actions.

Also minor nit (if we decide to keep this check) change `ActionExtession` to `ActionExtension`

File: src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java [hunk 2]
```diff
@@ -227,4 +237,29 @@ public void onFailure(Exception e) {
...
+                }
+
+                @Override
+                public void onFailure(Exception e) {
+                    responseFuture.completeExceptionally(e);
+                }
+            })
+        );
+
+        assertEquals("SDKClient was not initialized because the Extension does not implement ActionExtession.", ex.getMessage());
```
Comment (owaiskazi19) [inline src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java:263]:
```suggestion
        assertEquals("SDKClient was not initialized because the Extension does not implement ActionExtension.", ex.getMessage());
```

Comment (dbwiddis) [reply src/test/java/org/opensearch/sdk/sample/helloworld/TestHelloWorldExtension.java:263]: To my credit I had a test case making sure the typo was there too.

**Review by joshpalis — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]

File: src/main/java/org/opensearch/sdk/SDKClient.java (hunk 1 above)
Comment (dbwiddis) [reply src/main/java/org/opensearch/sdk/SDKClient.java:256]: Good point about the OpenSearch actions.  They probably have their own injected constructor values on the OpenSearch side so might need to actually be remotely executed on OS node client. 

Will look into that as part of #467 work.
