### PR TITLE
Miscellaneous Spotbugs issues

### LINKED ISSUE #552: [BUG] Miscellaneous Spotbugs issues
### What is the bug?

SpotBugs has identified some issues we should fix.

### How can one reproduce the bug?

1. Temporarily install the spotbugs gradle plugin in build.gradle:
```groovy
plugins {
  id "com.github.spotbugs" version "5.0.13"
}
```

2. Run `gradle check`
3. Filter out intentional issues.

### What is the expected behavior?

No unintended bugs

### Do you have any additional context?

Each of these should be evaluated and fixed.

 - [ ]  Exception is caught when Exception is not thrown in org.opensearch.sdk.handlers.UpdateSettingsRequestHandler.handleUpdateSettingsRequest(UpdateSettingsRequest)  At UpdateSettingsRequestHandler.java:[line 105]
 - [ ]  Uninitialized read of extensions in new org.opensearch.sdk.handlers.ExtensionDependencyResponseHandler()  At ExtensionDependencyResponseHandler.java:[line 41]
 - [ ]  Self assignment of field ExtensionDependencyResponseHandler.extensions in new org.opensearch.sdk.handlers.ExtensionDependencyResponseHandler()  At ExtensionDependencyResponseHandler.java:[line 41]
 - [ ]  Found reliance on default encoding in org.opensearch.sdk.TransportCommunicationIT$1.run(): new java.io.PrintStream(OutputStream)  At TransportCommunicationIT.java
 - [ ]  Found reliance on default encoding in org.opensearch.sdk.TransportCommunicationIT$1.run(): new java.io.InputStreamReader(InputStream)  At TransportCommunicationIT.java
 - [ ]  Should org.opensearch.sdk.TestBaseExtension$TestExtension be a _static_ inner class?  At TestBaseExtension.java:[lines 28-30]
 - [ ]  Should org.opensearch.sdk.TestExtensionRestHandler$NoOpExtensionRestHandler be a _static_ inner class?  At TestExtensionRestHandler.java:[lines 18-22]
 - [ ]  org.opensearch.sdk.ExtensionsRunnerForTest.NODE_NAME isn't final but should be  At ExtensionsRunnerForTest.java:[line 19]
 - [ ]  org.opensearch.sdk.ExtensionsRunnerForTest.NODE_HOST isn't final but should be  At ExtensionsRunnerForTest.java:[line 20]
 - [ ]  org.opensearch.sdk.ExtensionsRunnerForTest.NODE_PORT isn't final but should be  At ExtensionsRunnerForTest.java:[line 21]

### PR DESCRIPTION
**Pull request by Kuanysh-kst**
### Description
SpotBugs has identified some issues

### Issues Resolved

Fixes #552 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by owaiskazi19** [comment]
@Kuanysh-kst thanks for the PR. Can you link the issue this PR is for in the PR description under the title `Issues Resolved` and provide a description about this PR under `Description`. This will help the maintainers to understand the context of the PR. Thanks again.

File: src/test/java/org/opensearch/sdk/TransportCommunicationIT.java [hunk 1]
```diff
@@ -63,13 +64,13 @@ public void testSocketSetup() throws IOException {
 
             // check bound addresses
             for (TransportAddress transportAddress : transport.boundAddress().boundAddresses()) {
-                assert (transportAddress instanceof TransportAddress);
+                assert (transportAddress != null);
```
Comment (dbwiddis) [inline src/test/java/org/opensearch/sdk/TransportCommunicationIT.java:67]: Better to use `assertNotNull()` here (and elsewhere with this same pattern)

File: src/main/java/org/opensearch/sdk/handlers/UpdateSettingsRequestHandler.java [hunk 2]
```diff
@@ -99,9 +99,9 @@ public AcknowledgedResponse handleUpdateSettingsRequest(UpdateSettingsRequest up
                 case Version:
                     Consumer<Version> versionConsumer = (Consumer<Version>) this.settingUpdateConsumers.get(componentSetting);
                     versionConsumer.accept((Version) data);
-                default:
-                    throw new UnsupportedOperationException("Setting Update Consumer type does not exist and is not handled here");
             }
+        } catch (UnsupportedOperationException e) {
+            throw new UnsupportedOperationException("Setting Update Consumer type does not exist and is not handled here");
```
Comment (dbwiddis) [inline src/main/java/org/opensearch/sdk/handlers/UpdateSettingsRequestHandler.java:104]: I'm used to _always_ including a `default` in switch/case statements, even when it will never happen.  

I'm not sure I understand the reason for this change, or what it fixes. Could you explain the benefit of your change here?

**Review by dbwiddis — COMMENTED** [review]
Thanks for resubmitting this in a smaller commit!

One small request and one "I'm really not sure what this change does" comment.

**Comment by dbwiddis** [comment]
> @Kuanysh-kst thanks for the PR. Can you link the issue this PR is for in the PR description under the title `Issues Resolved` and provide a description about this PR under `Description`. This will help the maintainers to understand the context of the PR. Thanks again.

Those links would help.  

FYI this is a smaller resubmit of #580 based on [my request here](https://github.com/opensearch-project/opensearch-sdk-java/pull/580#issuecomment-1474920040https://github.com/opensearch-project/opensearch-sdk-java/pull/580#issuecomment-1474920040) and the issue being addressed is #552.

File: src/main/java/org/opensearch/sdk/handlers/UpdateSettingsRequestHandler.java (hunk 2 above)
Comment (Kuanysh-kst) [reply src/main/java/org/opensearch/sdk/handlers/UpdateSettingsRequestHandler.java:104]: these changes were made to remove this: An exception is intercepted when an exception is not generated in the org.opensearch.sdk.handlers settings.Update in UpdateSettingsRequestHandler.java :[line 105]

Comment (dbwiddis) [reply src/main/java/org/opensearch/sdk/handlers/UpdateSettingsRequestHandler.java]: > these changes were made to remove this: An exception is intercepted when an exception is not generated in the org.opensearch.sdk.handlers settings.Update in UpdateSettingsRequestHandler.java :[line 105]

OK, this is one of those cases where with the existing code, the exception will never be thrown (thus spotbugs complains).  But if someone makes code changes elsewhere and doesn't handle them here, this exception will alert the developer that they forgot something.

So there's no need to change anything here.  If there's a way to add a configuration to suppress spotbugs on this issue, that'd be preferred.

Comment (Kuanysh-kst) [reply src/main/java/org/opensearch/sdk/handlers/UpdateSettingsRequestHandler.java]: is it possible to add an additional catch(Runtimeexception e) to remove this warning because the @SuppressWarning("all") annotation or  unchecked, unused or other options do not work with this annotation

File: src/test/java/org/opensearch/sdk/TransportCommunicationIT.java [hunk 3]
```diff
@@ -63,13 +64,13 @@ public void testSocketSetup() throws IOException {
...
             for (TransportAddress transportAddress : transport.boundAddress().boundAddresses()) {
-                assert (transportAddress instanceof TransportAddress);
+                assertNotNull(transportAddress);
                 assertEquals(host, transportAddress.getAddress());
                 assertEquals(port, transportAddress.getPort());
             }
 
             // check publish addresses
-            assert (transport.boundAddress().publishAddress() instanceof TransportAddress);
+            assert (transport.boundAddress().publishAddress() != null);
```
Comment (dbwiddis) [inline src/test/java/org/opensearch/sdk/TransportCommunicationIT.java:73]: Would be better as an assertNotNull like the change 5 lines above. :)

**Review by dbwiddis — APPROVED** [review]
Approved. One suggestion but ok if this is merged without that change.

**Review by dbwiddis — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]
LGTM! Thanks @Kuanysh-kst for your contribution!
